<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.dk900912</groupId>
        <artifactId>multi-tier-cache-framework</artifactId>
        <version>1.0.0-M6</version>
    </parent>

    <artifactId>cache-core</artifactId>
    <name>cache-core</name>
    <description>The Core module of multi-tier-cache-framework</description>

    <dependencies>
        <dependency>
            <groupId>io.github.dk900912</groupId>
            <artifactId>cache-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.dk900912</groupId>
            <artifactId>cache-codec</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.dk900912</groupId>
            <artifactId>cache-provider-l1-jdk</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.dk900912</groupId>
            <artifactId>cache-provider-l2-jedis</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.dk900912</groupId>
            <artifactId>cache-provider-l2-lettuce</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.github.dk900912</groupId>
            <artifactId>cache-provider-l2-redisson</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
